machine:
  node:
    version: 6.11.4
test:
  override:
    - npm test -- --coverage
  post:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
    
deployment:
  staging:
    branch: master
    heroku:
      appname: marketcoin
